apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 80
    protocol: TCP
    targetPort: 4443
  selector:
    k8s-app: metrics-server
